def precisao(audio_dub, resultados_similaridade):
    if not resultados_similaridade:
        return 0
    recuperadas_relevantes = sum(1 for r in resultados_similaridade if r[1] == audio_dub)
    return recuperadas_relevantes / len(resultados_similaridade)

def revocacao(audio_dub, resultados_similaridade):
    dubladores= [
        ["Agatha", "Karen Padrão", "Feminino", "Adulto"],
        ["Jaser", "Raphael Rossatto", "Masculino", "Adulto"],
        ["Mia", "Pamella Rodrigues", "Feminino", "Adulto"],
        ["Samuel", "Fred Mascarenhas", "Masculino", "Adulto"],
        ["Verissimo", "Guilherme Briggs", "Masculino", "Adulto"],
        ["Aatrox", "Hércules Franco	", "Masculino", "Adulto"],
        ["Ahri","Miriam Ficher", "Feminino", "Adulto"],
        ["Akali", "Adriana Torres", "Feminino", "Adulto"],
        ["Akshan", "Fábio Azevedo", "Masculino", "Adulto"],
        ["Alistar", "Leo Rabelo", "Masculino", "Adulto"],
        ["Ambessa", "Marilza Batista", "Feminino", "Adulto"],
        ["Amumu", "Luiz Sergio Vieira", "Masculino", "Adulto"],
        ["Anivia", "Lucia Helena", "Feminino", "Adulto"],
        ["Annie", "Helena Palomanes", "Feminino", "Adulto"],
        ["Ashe", "Marcia Morelli", "Feminino", "Adulto"],
        ["Aurelion Sol", "Gilberto Barolli", "Masculino", "Adulto"],
        ["Aurora","Mari Haruno", "Feminino", "Adulto"],
        ["Azir", "Fabio de Castro", "Masculino", "Adulto"],
        ["BelVeth", "Marlene Costa", "Feminino", "Adulto"],
        ["Blitzcrank", "Leonardo Santhos", "Masculino", "Adulto"],
        ["Brand", "Eduardo Dascar", "Masculino", "Adulto"],
        ["Braum", "Jonas Mello", "Masculino", "Adulto"],
        ["Briar", "Fernanda Barone", "Feminino", "Adulto"],
        ["Caitlyn", "Mabel Cezar", "Feminino", "Adulto"],
        ["Camille", "Roseli Silva", "Feminino", "Adulto"],
        ["Cassiopeia", "Luciana Baroli", "Feminino", "Adulto"],
        ["Corki", "Isaac Bardavid", "Masculino", "Idoso"],
        ["Darius", "Ricardo Telles", "Masculino", "Adulto"],
        ["Diana", "Rosa Maria Baroli", "Feminino", "Adulto"],
        ["DrMundo", "Nardo Sierpe", "Masculino", "Adulto"],
        ["Draven", "Ricardo Juarez", "Masculino", "Adulto"],
        ["Ekko", "Marcelo Campos", "Masculino", "Adulto"],
        ["Evelyn", "Luisa Palomanes", "Feminino", "Adulto"],
        ["Ezreal", "Anderson Oliveira", "Masculino", "Adulto"],
        ["Fiora", "Marli Bortoletto", "Feminino", "Adulto"],
        ["Fizz", "Rodrigo Antas", "Masculino", "Adulto"],
        ["Galio", "Élcio Romar", "Masculino", "Adulto"],
        ["Gangplank", "Luiz Carlos Persy", "Masculino", "Adulto"],
        ["Garen", "Gutemberg Barros", "Masculino", "Adulto"],
        ["Gnar", "Úrsula Bezerra", "Feminino", "Infantil"],
        ["Gragas", "Flávio Back", "Masculino", "Adulto"],
        ["Graves", "Élcio Romar", "Masculino", "Adulto"],
        ["Heimerdinger", "André Belizar", "Masculino", "Adulto"],
        ["Illaoi", "Luísa Viegas", "Feminino", "Adulto"],
        ["Irelia", "Mariana Torres", "Feminino", "Adulto"],
        ["Janna", "Jullie Vasconcelos", "Feminino", "Adulto"],
        ["JarvanIV", "Christiano Torreão", "Masculino", "Adulto"],
        ["Jax", "Waldyr Sant'anna", "Masculino", "Adulto"],
        ["Jayce", "Malta Júnior", "Masculino", "Adulto"],
        ["Jinx", "Fernanda Bullara", "Feminino", "Adulto"],
        ["Kalista", "Calista Helena", "Feminino", "Adulto"],
        ["Karma", "Marize Motta", "Feminino", "Adulto"],
        ["Karthus", "Isaac Bardavid", "Masculino", "Idoso"],
        ["Katarina", "Silvia Goiabeira", "Feminino", "Adulto"],
        ["Kayle", "Carla Pompílio", "Feminino", "Adulto"],
        ["Kennen", "Luisa Palomanes", "Feminino", "Adulto"],
        ["LeBlanc", "Carol Crespo", "Feminino", "Adulto"],
        ["LeeSin", "Wendel Bezerra", "Masculino", "Adulto"],
        ["Leona", "Angélica Borges", "Feminino", "Adulto"],
        ["Lissandra", "Alessandra Araújo", "Feminino", "Adulto"],
        ["Lucian", "Marco Antônio Abreu", "Masculino", "Adulto"],
        ["Lulu", "Pamella Rodrigues", "Feminino", "Infantil"],
        ["Lux", "Cristiane Monteiro", "Feminino", "Adulto"],
        ["Maokai", "Waldyr Sant'anna", "Masculino", "Adulto"],
        ["MasterYi", "Dário de Castro", "Masculino", "Adulto"],
        ["MissFortune", "Maíra Góes", "Feminino", "Adulto"],
        ["Morgana", "Marisa Leal", "Feminino", "Adulto"],
        ["Nami", "Michelle Giudice", "Feminino", "Adulto"],
        ["Nasus", "Renato Rosenberg", "Masculino", "Adulto"],
        ["Nautilus", "Sérgio Fortuna", "Masculino", "Adulto"],
        ["Nidalee", "Rita Lopes", "Feminino", "Adulto"],
        ["Nunu", "Matheus Caliano", "Masculino", "Infantil"],
        ["Olaf", "Mauro Ramos", "Masculino", "Adulto"],
        ["Pantheon", "Mário Tupinambá", "Masculino", "Adulto"],
        ["Poppy", "Marisa Leal", "Feminino", "Infantil"],
        ["Quinn", "Jussara Marques", "Feminino", "Adulto"],
        ["Renekton", "Jorge Vasconcellos", "Masculino", "Adulto"],
        ["Riven", "Melissa Garcia", "Feminino", "Adulto"],
        ["Rumble", "Renan Freitas", "Masculino", "Adulto"],
        ["Ryze", "Jorge Vasconcellos", "Masculino", "Adulto"],
        ["Sejuani", "Mônica Rossi", "Feminino", "Adulto"],
        ["Shaco", "Márcio Simões", "Masculino", "Adulto"],
        ["Shen", "Ettore Zuim", "Masculino", "Adulto"],
        ["Shyvana", "Carmen Sheila", "Feminino", "Adulto"],
        ["Singed", "Francisco José", "Masculino", "Adulto"],
        ["Sion", "Gutemberg Barros", "Masculino", "Adulto"],
        ["Sivir", "Christiane Louise", "Feminino", "Adulto"],
        ["Skarner", "Márcio Simões", "Masculino", "Adulto"],
        ["Sona", "Aline Ghezzi", "Feminino", "Adulto"],
        ["Soraka", "Izabel Lira", "Feminino", "Adulto"],
        ["Swain", "Carlos Seidl", "Masculino", "Adulto"],
        ["Syndra", "Raquel Marinho", "Feminino", "Adulto"],
        ["TahmKench", "Mauro Castro", "Masculino", "Adulto"],
        ["Talon", "Leo Rabelo", "Masculino", "Adulto"],
        ["Taric", "Duda Espinoza", "Masculino", "Adulto"],
        ["Teemo", "Eduardo Drummond", "Masculino", "Infantil"],
        ["Thresh", "César Marchetti", "Masculino", "Adulto"],
        ["Tristana", "Carol Kapfer", "Feminino", "Infantil"],
        ["Trundle", "Ronaldo Júlio", "Masculino", "Adulto"],
        ["Tryndamere", "Maurício Berger", "Masculino", "Adulto"],
        ["Twisted Fate", "Eduardo Dascar", "Masculino", "Adulto"],
        ["Twitch", "José Leonardo", "Masculino", "Adulto"],
        ["Udyr", "Walmir Barbosa", "Masculino", "Adulto"],
        ["Urgot", "Flávio Back", "Masculino", "Adulto"],
        ["Varus", "Paulo Vignolo", "Masculino", "Adulto"],
        ["Vayne", "Priscila Amorim", "Feminino", "Adulto"],
        ["Veigar", "Pedro Lopes", "Masculino", "Infantil"],
        ["VelKoz", "Leonardo Santhos", "Masculino", "Adulto"],
        ["Vi", "Tatiane Keplmair", "Feminino", "Adulto"],
        ["Viktor", "Francisco José", "Masculino", "Adulto"],
        ["Vladimir", "Ricardo Schnetzer", "Masculino", "Adulto"],
        ["Volibear", "José Santa Cruz", "Masculino", "Adulto"],
        ["Warwick", "Luiz Carlos Persy", "Masculino", "Adulto"],
        ["Wukong", "Leonardo Santhos", "Masculino", "Adulto"],
        ["Xerath", "Pietro Mário", "Masculino", "Adulto"],
        ["XinZhao", "Júlio Chaves", "Masculino", "Adulto"],
        ["Yasuo", "Marco Antônio Abreu", "Masculino", "Adulto"],
        ["Yorick", "Mauro Ramos", "Masculino", "Adulto"],
        ["Zac", "Affonso Amajones", "Masculino", "Adulto"],
        ["Zed", "Zeca Rodrigues", "Masculino", "Adulto"],
        ["Ziggs", "Pedro Eugênio", "Masculino", "Adulto"],
        ["Zilean", "Pietro Mário", "Masculino", "Idoso"],
        ["Zyra", "Fernanda Crispim", "Feminino", "Adulto"]
        ]
    relevantes = sum(1 for i in dubladores if i[1] == audio_dub)
    if relevantes == 0:
        return 0
    recuperadas_relevantes = sum(1 for i in resultados_similaridade if i[1] == audio_dub)
    return recuperadas_relevantes / relevantes
